### ISSUE TITLE
get_mix_ids API is broken

### ISSUE THREAD

**Issue by hkpanchani** [brandonbondig/growatt-api#4]
API call:
```
mixSn = api.get_mix_ids(plantId)
print(mixSn)
```

Error Response:
```
Traceback (most recent call last):
  File "/tmp/lwnlfpqrri/main.py", line 12, in <module>
    mixSn = api.get_mix_ids(plantId)[0][1]
  File "/home/debos/.local/lib/python3.10/site-packages/growatt/__init__.py", line 155, in get_mix_ids
    json_res = res.json()['obj']["mix"]
KeyError: 'mix'
```

**Comment by siebrink** [comment]
Same issue found overhere.  Somehow this get_mix_ids API request doesn't work or is not recognized.

**Comment by brandonbondig** [comment]
Please see issue #1, this might be related.

**Comment by siebrink** [comment]
Hello, I just checked your response regarding issuer #1, still experience same issue.
Result of "plant_id - api.get_plants()"

Response:

/usr/local/bin/python3.9 /Users/siebrink/pythonProjects2025/Growatt/Initialize.py 
[{'timezone': ‘X', 'id': ‘XXXX', 'plantName': ‘XXXXX'}]

Process finished with exit code 0

Off course I have removed the 'private' output (X) but here I don't experience any error. Output looks correct.

But adding "mix_ids = api.get_mix_ids(plant_id)"

Response:

{'timezone': ‘X', 'id': ‘XXXX', 'plantName': ‘XXXXX'}]
Traceback (most recent call last):
  File "/Users/siebrink/pythonProjects2025/Growatt/Initialize.py", line 10, in <module>
    mix_ids = api.get_mix_ids(plant_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/growatt/__init__.py", line 153, in get_mix_ids
    res.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: [https://openapi.growatt.com//panel/getDevicesByPlant?plantId=%5B%7B'timezone':%20'](https://openapi.growatt.com//panel/getDevicesByPlant?plantId=%5B%7B%27timezone%27:%20%27)X',%20'id':%20'XXXX',%20'plantName':%20'XXXXX'%7D%5D

**Comment by kumerian** [comment]
Same here. Erroring out on the ["mix"] element even though there is a plant available

I have 2 inverters. When I call the endpoint that is used for this, it returns one of the as "tlx", one as "max", no entries "mix" in the JSON.

**Comment by brandonbondig** [comment]
Hello, sorry for the late response to this matter. For @siebrink, the error you're experiencing looks like you parsed the whole object returned by `get_plants()`, i.e you accidentally placed `[{'timezone': ‘X', 'id': ‘XXXX', 'plantName': ‘XXXXX'}]` as the input argument in get_mix_ids(plant_id), evidently by looking at this error:

>requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: [openapi.growatt.com//panel/getDevicesByPlant?plantId=%5B%7B%27timezone%27:%20%27](https://openapi.growatt.com//panel/getDevicesByPlant?plantId=%5B%7B%27timezone%27:%20%27) --->X',%20'id':%20'XXXX',%20'plantName':%20'XXXXX'%7D%5D <--- 

heres what you are supposed to do:
```python
from growatt import Growatt

client = Growatt()
client.login('username', 'password')

print(client.get_plants())
````

this returns:
`[{'timezone': '2', 'id': '123456', 'plantName': 'Brandon Bondig}]`

you are then supposed to take the value of 'id', in this case '123456' and place that id as the input argument:

```python
print(client.get_mix_ids("123456"))
```

this returns the mix id's.

hopefully this also fixes your problem @kumerian
